apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo
  name: echo
spec:
  selector:
    matchLabels:
      app: echo
  replicas: 1
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - image: ghcr.io/huangyingting/echo:latest
        imagePullPolicy: Always
        name: echo
        ports:
        - containerPort: 8080
        env:
          - name: ENVIRONMENT
            value: none
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    app: echo  
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: echo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  name: echo
spec:
  ingressClassName: nginx
  rules:
  - host: echo.example.com
    http:
      paths:
      - backend:
          service: 
            name: echo
            port: 
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - echo.example.com
    secretName: echo-tls
